[[classOrder]]
classes = ["Util"]

[[classOrder]]
section = "Components"
classes = [
  "Base",
  "Button",
  "Frame",
  "BaseButton",
  "IconButton",
  "Card",
  "CanvasGroup",
  "MenuFrame",
  "SwitchInput",
  "SwitchGroup",
  "Text",
  "Badge",
  "ScrollingFrame",
  "Checkbox",
  "TextInput",
  "TextArea",
  "Avatar",
  "ProgressBar",
  "TitleBar",
  "Icon",
  "Divider",
  "AutoScaleFrame",
  "Image",
  "NumberSpinner",
  "IconText",
]

[docusaurus]
title = "OnyxUI"
tagline = "Quick, quality UI components for Fusion"
url = "https://avafe.me/"
favicon = "/favicon.svg"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "High quality components üß©"
description = "Make quality UI faster with dozens of fully-typed components."

[[home.features]]
title = "Comprehensive theming üé®"
description = "Give your UI the look and feel you desire with OnyxUI's featureful theming system."

[[home.features]]
title = "Styling, now *not* stupid üñåÔ∏è"
description = "Screw messy markup. Style any component, with less code, using OnyxUI's passthrough styling props."

[footer]
style = "dark"
copyright = "Copyright ¬© 2024 Avafe. Built with Moonwave and Docusaurus"

# [[classOrder]]
# section = "Util"
# collapsed = true
# classes = ["Colors", "EnsureValue"]
